### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ivashov** [oss-fruct-org/audioguide#10]
При попытке открыть недозагруженную точку

```
03-19 18:40:15.553  15916-15916/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.fruct.oss.audioguide, PID: 15916
    java.lang.NullPointerException
            at org.fruct.oss.audioguide.fragments.PanelFragment.setPausedState(PanelFragment.java:301)
            at org.fruct.oss.audioguide.fragments.PanelFragment.itemLoaded(PanelFragment.java:351)
            at org.fruct.oss.audioguide.files.FileManager$7.run(FileManager.java:282)
            at org.fruct.oss.audioguide.files.FileManager$9$1.run(FileManager.java:401)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5214)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:814)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ivashov** [comment]
Воспроизвести не удается, т.к. FileManager полностью обновлен, возможно что бага больше нет.
