### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ivashov** [oss-fruct-org/audioguide#12]
```
    java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
            at java.util.ArrayList.get(ArrayList.java:310)
            at android.support.v4.app.FragmentManagerImpl.getBackStackEntryAt(FragmentManager.java:552)
            at org.fruct.oss.audioguide.MainActivity.onBackPressed(MainActivity.java:236)
            at android.app.Activity.onKeyUp(Activity.java:2193)
```

**Comment by ivashov** [comment]
Воспроизвести не удается. Возможно какие-то гонки в FragmentManagere.
